name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and build frontend
        run: |
          cd web-app/frontend
          npm ci
          npm run build --if-present
          npm test

      - name: Install dependencies and test backend
        run: |
          cd web-app/backend
          npm ci
          npm test
